#spring.application.name=apipedidos
#server.port=8090
#
## Configuraci?n de conexi?n a MariaDB
#spring.datasource.url=jdbc:mariadb://localhost:3306/dbpedidos?serverTimezone=America/Lima
#spring.datasource.username=admin
#spring.datasource.password=admin123
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#
## Configuraci?n JPA/Hibernate
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# Configuraci?n para PostgreSQL
spring.application.name=apipedidos
server.port=8090

# Configuracion de conexion a PostgreSQL
# Nota: PostgreSQL no soporta 'createDatabaseIfNotExist=true' en la URL como MySQL/MariaDB
spring.datasource.url=jdbc:postgresql://localhost:5432/dbpedidos?currentSchema=public
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Dialecto especifico para las versiones modernas de PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

